# docker-compose.yml
version: '3.8'

services:
  gateway:
    image: nginx:latest
    container_name: nginx-gateway
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./infra/gateway/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    restart: unless-stopped
    environment:
      DB_HOST: db1
      DB_DATABASE: service1
      DB_USERNAME: root
      DB_PASSWORD: root
    volumes:
      - ./auth-service:/var/www/html
    networks:
      - laravel

  db1:
    image: mysql:8.0
    container_name: mysql-service1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: service1
      MYSQL_USER: service1user
      MYSQL_PASSWORD: service1password
    networks:
      - laravel


volumes:
  db1_data:

networks:
  laravel:
    driver: bridge
