# docker-compose.yml
version: '3.8'

services:
  gateway:
    image: nginx:latest
    container_name: nginx-gateway
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./infra/gateway/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    restart: unless-stopped
    environment:
      DB_HOST: auth-service-db
      DB_DATABASE: auth-service
      DB_USERNAME: root
      DB_PASSWORD: root 
    volumes:
      - ./auth-service:/var/www/html
    networks:
      - laravel
    ports:
      - "8004:8000"  

  note-service:
    build:
      context: ./note-taking-service
      dockerfile: Dockerfile
    container_name: note-service
    restart: unless-stopped
    environment:
      DB_HOST: note-service-db
      DB_DATABASE: note-service
      DB_USERNAME: root
      DB_PASSWORD: root
    volumes:
      - ./note-taking-service:/var/www/html
    networks:
      - laravel
    ports:
      - "8005:8000"
  note-service-worker:
    build:
      context: ./note-taking-service
      dockerfile: Dockerfile
    container_name: note-service-worker
    restart: unless-stopped
    environment:
      DB_HOST: note-service-db
      DB_DATABASE: note-service
      DB_USERNAME: root
      DB_PASSWORD: root
    volumes:
      - ./note-taking-service:/var/www/html
      - /var/www/html/vendor
    networks:
      - laravel
    entrypoint: ["/bin/bash","entrypoint_worker.sh"]
    depends_on:
      - rabbitmq
      - note-service-db


  auth-service-db:
    image: mysql:8.0
    container_name: mysql-service1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth-service
      MYSQL_USER: auth-service-user
      MYSQL_PASSWORD: auth-service-password
    networks:
      - laravel

  note-service-db:
    image: mysql:8.0
    container_name: mysql-service2
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: note-service
      MYSQL_USER: note-service-user
      MYSQL_PASSWORD: note-service-password
    networks:
      - laravel
      
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ default port
      - "15672:15672" # RabbitMQ Management plugin default port    
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - laravel




volumes:
  db1_data:

networks:
  laravel:
    driver: bridge
