name: Test Microservices

on:
  pull_request:
    paths:
      - "note-taking-service/**"
jobs:      
  test-note-taking-service:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: note-taking-service_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0

      - name: Install dependencies
        run: |
          cd note-taking-service
          cp .env.example .env
          composer install
          php artisan key:generate
          php artisan migrate

      - name: Run tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: note-taking-service_db
          DB_USERNAME: root
          DB_PASSWORD: root
        run: cd note-taking-service && php artisan test
