name: Test Microservices

on:
  pull_request:
    paths:
      - 'auth-service/**'
      - 'note-taking-service/**'

jobs:
  test-auth-service:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.head.ref, 'auth-service') || github.event.pull_request.changed_files == 0 || github.event.pull_request.changed_files contains 'auth-service/'

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: auth-service_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0

    - name: Install dependencies
      run: |
        cd auth-service
        cp .env.example .env
        composer install
        php artisan key:generate
        php artisan migrate

    - name: Run tests
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: auth-service_db
        DB_USERNAME: root
        DB_PASSWORD: root
      run: cd auth-service && php artisan test

  test-note-taking-service:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.head.ref, 'note-taking-service') || github.event.pull_request.changed_files == 0 || github.event.pull_request.changed_files contains 'note-taking-service/'

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: note-taking-service_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0

    - name: Install dependencies
      run: |
        cd note-taking-service
        cp .env.example .env
        composer install
        php artisan key:generate
        php artisan migrate

    - name: Run tests
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: note-taking-service_db
        DB_USERNAME: root
        DB_PASSWORD: root
      run: cd note-taking-service && php artisan test
