name: Test Microservices

on:
  pull_request:
    paths:
      - 'auth-service/**'
      - 'note-taking-service/**'

jobs:
  determine-changes:
    runs-on: ubuntu-latest
    outputs:
      auth-service-changed: ${{ steps.auth-service-changed.outputs.changed }}
      note-taking-service-changed: ${{ steps.note-taking-service-changed.outputs.changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for changes in auth-service
        id: auth-service-changed
        uses: dorny/paths-filter@v2
        with:
          filters: |
            auth-service:
              - 'auth-service/**'

      - name: Check for changes in note-taking-service
        id: note-taking-service-changed
        uses: dorny/paths-filter@v2
        with:
          filters: |
            note-taking-service:
              - 'note-taking-service/**'

  test-auth-service:
    needs: determine-changes
    if: needs.determine-changes.outputs['auth-service-changed'] == 'true'
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: auth_service_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0

      - name: Install dependencies
        run: |
          cd auth-service
          cp .env.example .env
          composer install
          php artisan key:generate
          php artisan migrate

      - name: Run tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: auth_service_db
          DB_USERNAME: root
          DB_PASSWORD: root
        run: cd auth-service && php artisan test

  test-note-taking-service:
    needs: determine-changes
    if: needs.determine-changes.outputs['note-taking-service-changed'] == 'true'
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: note_taking_service_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0

      - name: Install dependencies
        run: |
          cd note-taking-service
          cp .env.example .env
          composer install
          php artisan key:generate
          php artisan migrate

      - name: Run tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: note_taking_service_db
          DB_USERNAME: root
          DB_PASSWORD: root
        run: cd note-taking-service && php artisan test
